POST http://localhost:3000/teams/generate/team3
content-type: application/json

{
    "timestamp" : "2018-04-19 00:00:00",
    "members" : ["player 1","player 2","player 3"]
}
###
GET http://localhost:3000/teams/icons