POST http://localhost:3000/teams/generate/team1
content-type: application/json
###
POST http://localhost:3000/teams/generate/team2
content-type: application/json
###
POST http://localhost:3000/teams/generate/team3
content-type: application/json
###
GET  http://localhost:3000/teams/get/team2

###
GET  http://localhost:3000/teams/get

###
POST  http://localhost:3000/teams/siam
Content-Type: application/json

{
    "team1" : 2,
    "team2" : 3
}